color0                  #34343a
color1                  #ffb4ab
color2                  #c2c5dd
color3                  #e3bada
color4                  #c2c5dd
color5                  #4d5c92
color6                  #2345be
color7                  #e3e1e9
color8                  #90909a
color9                  #ffcbc5
color10                 #cdd1eb
color11                 #f3c3e9
color12                 #c0c5ec
color13                 #657ac6
color14                 #4b67c9
color15                 #fefeff

cursor                  #b6c4ff
cursor_text_color       #121318
background              #000000
foreground              #e3e1e9
selection_foreground    #c6c6d0
selection_background    #45464f
url_color               #b6c4ff

tab_bar_margin_color    #121318
tab_bar_background      #121318
active_tab_foreground   #1d2d61
active_tab_background   #b6c4ff
inactive_tab_foreground #c6c6d0
inactive_tab_background #1d2d61

active_border_color     #b6c4ff
inactive_border_color   #45464f
