color0                  #34343a
color1                  #ffb4ab
color2                  #c4c5dd
color3                  #e6bad7
color4                  #c4c5dd
color5                  #525a92
color6                  #283bbe
color7                  #e4e1e9
color8                  #90909a
color9                  #ffcbc5
color10                 #cfd0eb
color11                 #f5c4e5
color12                 #c2c4ec
color13                 #6c77c5
color14                 #5362c6
color15                 #fefeff

cursor                  #bbc3ff
cursor_text_color       #131318
background              #000000
foreground              #e4e1e9
selection_foreground    #c7c5d0
selection_background    #46464f
url_color               #bbc3ff

tab_bar_margin_color    #131318
tab_bar_background      #131318
active_tab_foreground   #232c61
active_tab_background   #bbc3ff
inactive_tab_foreground #c7c5d0
inactive_tab_background #232c61

active_border_color     #bbc3ff
inactive_border_color   #46464f
