color0                  #35343a
color1                  #ffb4ab
color2                  #c7c4dc
color3                  #eab9d1
color4                  #c7c4dc
color5                  #5b5891
color6                  #362ebd
color7                  #e5e1e9
color8                  #928f99
color9                  #ffcbc5
color10                 #d2cfeb
color11                 #f8c4de
color12                 #c7c2eb
color13                 #7773c2
color14                 #625cc2
color15                 #fffeff

cursor                  #c4c0ff
cursor_text_color       #131318
background              #000000
foreground              #e5e1e9
selection_foreground    #c8c5d0
selection_background    #47464f
url_color               #c4c0ff

tab_bar_margin_color    #131318
tab_bar_background      #131318
active_tab_foreground   #2c2960
active_tab_background   #c4c0ff
inactive_tab_foreground #c8c5d0
inactive_tab_background #2c2960

active_border_color     #c4c0ff
inactive_border_color   #47464f
