# =============== Appearance ===============
include kittycolors.conf
font_family      MesloLGM Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

# Remote control 
allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration enabled 

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'

# Browse scrollback buffer in nvim
map ctrl+shift+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map ctrl+shift+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

# Set window size (in cells) on startup
initial_window_width  100c
initial_window_height 30c

# Rounded corners and padding (good for Wayland compositors)
window_padding_width  0
background_opacity    0.4
draw_minimal_borders  yes

# Use system notifications on bell
enable_audio_bell no
visual_bell_duration 0.2

# =============== Scrolling and Clipboard ===============

scrollback_lines 5000
wheel_scroll_multiplier 5.0
touch_scroll_multiplier 2.0

# Copy on select,
copy_on_select yes

# Don't close window when shell exits
confirm_os_window_close 0

# =============== Performance ===============

# Enable GPU rendering (default)
repaint_delay 10
input_delay 1
sync_to_monitor yes

# =============== Keybindings (Optional) ===============
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# =============== Windows (Splits) ==================
map alt+enter launch --cwd=current
map alt+shift+enter new_window
map alt+z toggle_layout stack

# =============== Navigation(Splits) ======================
map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right 
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down

# =============== Resizing Windows ==================
map alt+shift+left  resize_window narrower 2
map alt+shift+right resize_window wider 2
map alt+shift+up    resize_window taller 2
map alt+shift+down  resize_window shorter 2
map alt+shift+backspace resize_window reset

# =============== Tabs ===============
map alt+shift+t new_tab
map alt+t launch --type=tab --cwd=current
map alt+shift+h previous_tab
map alt+shift+l next_tab
map alt+shift+i set_tab_title

# =============== Closing ===================
map alt+w close_window
map alt+shift+w close_tab

# ============== Font scaling ==================
map alt+backspace change_font_size current 0 

# =============== cycle layouts ===================
map alt+tab next_layout

# =============== Cursor trail ===============
cursor_trail 1
cursor_trail_decay 0.2 0.4
cursor_trail_start_threshold 1

# =============== Mouse Behaviour =============
mouse_hide_wait 1.0

# =============== Tabs =================
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
tab_bar_align left
tab_bar_min_tabs 2
tab_bar_margin_width 0.0
tab_bar_margin_height 2.5 1.5
inactive_tab_font_style normal
active_tab_font_style bold

tab_activity_symbol             " ● "

tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
