$lock_text = rgba(c5c6d0ff)
$border_color = rgba(8e9099ff)
$check_color = rgba(583e5aff)
$active_border = rgba(aec6ffff)
$inactive_border = rgba(44474fff)
$font_color = rgba(e2e2e9ff)
$glass_fill = rgba(44474f0d)
$glass_border = rgba(8e909926)
$subtle_text = rgba(c5c6d099)
