$lock_text = rgba(d4c2c7ff)
$border_color = rgba(9d8c92ff)
$check_color = rgba(633e23ff)
$active_border = rgba(feb0d1ff)
$inactive_border = rgba(504348ff)
$font_color = rgba(eedfe3ff)
$glass_fill = rgba(5043480d)
$glass_border = rgba(9d8c9226)
$subtle_text = rgba(d4c2c799)
