$lock_text = rgba(c8c5d0ff)
$border_color = rgba(918f9aff)
$check_color = rgba(603c50ff)
$active_border = rgba(c2c1ffff)
$inactive_border = rgba(47464fff)
$font_color = rgba(e5e1e9ff)
$glass_fill = rgba(47464f0d)
$glass_border = rgba(918f9a26)
$subtle_text = rgba(c8c5d099)
