[colors.normal]
# Background and subtle elements
black          = "#121318"
white          = "#e3e1e9"
bright_black   = "#90909a"

# Main data colors
# Using 'error' for Red, 'tertiary' for Yellow, 'primary' for Green
red            = "#ffb4ab"
yellow         = "#e5bad8"
green          = "#b9c3ff"
cyan           = "#c3c5dd"
blue           = "#384379"

# Accent colors
magenta        = "#505b92"
bright_red     = "#93000a"
bright_green   = "#dde1ff"
bright_yellow  = "#ffd7f3"
