[colors.normal]
# Background and subtle elements
black          = "#191113"
white          = "#efdee1"
bright_black   = "#9e8c8f"

# Main data colors
# Using 'error' for Red, 'tertiary' for Yellow, 'primary' for Green
red            = "#ffb4ab"
yellow         = "#edbe92"
green          = "#ffb1c3"
cyan           = "#e4bdc4"
blue           = "#713344"

# Accent colors
magenta        = "#8d4a5c"
bright_red     = "#93000a"
bright_green   = "#ffd9e0"
bright_yellow  = "#ffdcbe"
