[colors.normal]
# Background and subtle elements
black          = "#16130b"
white          = "#eae1d4"
bright_black   = "#989080"

# Main data colors
# Using 'error' for Red, 'tertiary' for Yellow, 'primary' for Green
red            = "#ffb4ab"
yellow         = "#aecfac"
green          = "#e5c36c"
cyan           = "#d6c5a0"
blue           = "#594400"

# Accent colors
magenta        = "#755b0b"
bright_red     = "#93000a"
bright_green   = "#ffdf94"
bright_yellow  = "#caebc7"
