[Service]
# Clear any existing ExecStart commands
ExecStart=
ExecStart=/usr/bin/mpd --systemd
ExecStartPre=
ExecStartPre=/usr/bin/rm -f %h/.config/mpd/socket
Restart=always
RestartSec=3
Environment=MPD_HOST=%h/.config/mpd/socket
