$lock_text = rgba(c6c5d0ff)
$border_color = rgba(90909aff)
$check_color = rgba(5c3d56ff)
$active_border = rgba(b7c4ffff)
$inactive_border = rgba(45464fff)
$font_color = rgba(e3e1e9ff)
$glass_fill = rgba(45464f0d)
$glass_border = rgba(90909a26)
$subtle_text = rgba(c6c5d099)
