# ── General settings ─────────────────────────────────────────────
general {
    lock_cmd = pidof hyprlock || hyprlock       # run hyprlock only if not already running
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # wake screen properly
    inhibit_sleep = 0                           # auto mode
}

# ── Listener: Dim screen after 3 min ──────────────────────────────
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}


# ── Listener: Lock screen after 3 min ─────────────────────────────
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# ── Listener: Turn off keyboard backlight after 3 min  ────────────
listener {
  timeout = 180
  on-timeout = brightnessctl -sd platform:kbd_backlight set 0
  on-resume  = brightnessctl -rd platform:kbd_backlight
}

# ── Listener: Turn off display after 5 min ────────────────────────
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# ── Listener: Pause Music on suspend ──────────────────────────────
listener {
    timeout = 1800
    on-timeout = playerctl pause
}

# ── Listener: Block wifi and bluetooth on suspend ─────────────────
listener {
    timeout = 1800
    on-timeout = rfkill block wifi && rfkill block bluetooth
    on-resume = rfkill unblock wifi && rfkill unblock bluetooth
}

# ── Listener: Suspend after 30 min ────────────────────────────────
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
