$lock_text = rgba(d6c3b6ff)
$border_color = rgba(9e8e82ff)
$check_color = rgba(444a22ff)
$active_border = rgba(ffb77aff)
$inactive_border = rgba(51443bff)
$font_color = rgba(efe0d6ff)
$glass_fill = rgba(51443b0d)
$glass_border = rgba(9e8e8226)
$subtle_text = rgba(d6c3b699)
