$lock_text = rgba(cfc5b4ff)
$border_color = rgba(989080ff)
$check_color = rgba(314d33ff)
$active_border = rgba(e5c36cff)
$inactive_border = rgba(4c4639ff)
$font_color = rgba(eae1d4ff)
$glass_fill = rgba(4c46390d)
$glass_border = rgba(98908026)
$subtle_text = rgba(cfc5b499)
