# ── General settings ─────────────────────────────────────────────
general {
    lock_cmd = pidof hyprlock || hyprlock       # run hyprlock only if not already running
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # wake screen properly
    inhibit_sleep = 0                           # auto mode
}

# ── Listener: Dim screen after 2.5 min ─────────────────────────────
listener {
    timeout = 150                                # 2.5 minutes
    on-timeout = brightnessctl -s set 10         # dim brightness
    on-resume = brightnessctl -r                 # restore brightness
}


# ── Listener: Lock screen after 3 min ─────────────────────────────
listener {
    timeout = 180
    on-timeout = loginctl lock-session
}

# ── Listener: Turn off keyboard backlight after 3.5 min  ──────────  
listener {
  timeout = 210
  on-timeout = brightnessctl -sd platform:kbd_backlight set 0
  on-resume  = brightnessctl -rd platform:kbd_backlight
}

# ── Listener: Turn off display after 5 min ────────────────────────
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# ── Listener: Suspend after 30 min ──────────────────────────────── 
# listener {
#     timeout = 1800
#     on-timeout = systemctl suspend
# }
