version = 4
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[upgrade]
source = 'cdn'
interval = '168h'
auto = false 
notice = false

[palette]
  blue = '#89b4fa'
  cyan = '#94e2d5'
  grey = '#6c6c6c'
  yellow = '#f9e2af'
  magenta = '#cba6f7'
  red = '#f38ba8'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'default'
    type = 'os'
    style = 'plain'
   
  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:blue'
    type = 'session'
    style = 'plain'
  
  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:magenta{{end}}",
    ]
    background = 'transparent'
    foreground = 'p:blue'
    template = '{{ .Path }}'
  
    [blocks.segments.options]
      folder_icon = '....'
      home_icon = '~'
      max_depth = 5
      style = 'agnoster_short' 

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if .Working.Changed }} <p:red>*{{add .Working.Modified .Working.Deleted .Working.Unmerged}}</>{{ end }}{{ if .Staging.Changed }} <p:magenta>+{{add .Staging.Modified .Staging.Deleted .Staging.Unmerged}}</>{{ end }}{{ if gt .Behind 0 }} <p:cyan>⇣</><p:yellow>{{ .Behind }}</>{{ end }}{{ if gt .Ahead 0 }} <p:cyan>⇡</><p:yellow>{{ .Ahead }}</>{{ end }}'

    [blocks.segments.options]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = 'blue'
    background = 'transparent'
    template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'
  
  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:magenta{{end}}",
  ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'p:magenta'
  background = 'transparent'
  template = '❯❯ '

