Ctrl+2 cycle-values tone-mapping "spline" "bt.2446a" "st2094-40" ; show-text "Tone-Map"
Ctrl+b cycle-values deband "yes" "no" ; show-text "deband"
F script-binding quality_menu/video_formats_toggle
Alt+f script-binding quality_menu/audio_formats_toggle
CTRL+B script-binding mpv_anilist_updater/launch_anilist
